name: Week8
version: 0.0.0

ghc-options: -Wall

dependencies:
 - base == 4.*
 - containers == 0.6.*

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: Week8
