name: Week7
version: 0.0.0

ghc-options: -Wall -fprint-potential-instances

dependencies:
 - base == 4.*
 - mtl

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: Week7
